// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alumno.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAlumno = `-- name: CreateAlumno :exec

INSERT INTO alumno (usuario_id, fecha_inscripcion, fecha_vto, tipo_plan, rutina_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAlumnoParams struct {
	UsuarioID        int32          `json:"usuario_id"`
	FechaInscripcion time.Time      `json:"fecha_inscripcion"`
	FechaVto         sql.NullTime   `json:"fecha_vto"`
	TipoPlan         sql.NullString `json:"tipo_plan"`
	RutinaID         sql.NullInt32  `json:"rutina_id"`
}

// CONSULTAS DE ALUMNO
func (q *Queries) CreateAlumno(ctx context.Context, arg CreateAlumnoParams) error {
	_, err := q.db.ExecContext(ctx, createAlumno,
		arg.UsuarioID,
		arg.FechaInscripcion,
		arg.FechaVto,
		arg.TipoPlan,
		arg.RutinaID,
	)
	return err
}

const getAlumnoCompleto = `-- name: GetAlumnoCompleto :one
SELECT
    u.id, u.email, u.nombre, u.apellido, u.telefono, u.rol, u.created_at,
    a.fecha_inscripcion, a.fecha_vto, a.tipo_plan, a.rutina_id
FROM usuario u
JOIN alumno a ON u.id = a.usuario_id
WHERE u.id = $1
`

type GetAlumnoCompletoRow struct {
	ID               int32          `json:"id"`
	Email            string         `json:"email"`
	Nombre           string         `json:"nombre"`
	Apellido         string         `json:"apellido"`
	Telefono         sql.NullString `json:"telefono"`
	Rol              string         `json:"rol"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	FechaInscripcion time.Time      `json:"fecha_inscripcion"`
	FechaVto         sql.NullTime   `json:"fecha_vto"`
	TipoPlan         sql.NullString `json:"tipo_plan"`
	RutinaID         sql.NullInt32  `json:"rutina_id"`
}

func (q *Queries) GetAlumnoCompleto(ctx context.Context, id int32) (GetAlumnoCompletoRow, error) {
	row := q.db.QueryRowContext(ctx, getAlumnoCompleto, id)
	var i GetAlumnoCompletoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.Apellido,
		&i.Telefono,
		&i.Rol,
		&i.CreatedAt,
		&i.FechaInscripcion,
		&i.FechaVto,
		&i.TipoPlan,
		&i.RutinaID,
	)
	return i, err
}

const listAlumnosCompletos = `-- name: ListAlumnosCompletos :many
SELECT
    u.id, u.email, u.nombre, u.apellido, u.telefono, u.rol, u.created_at,
    a.fecha_inscripcion, a.fecha_vto, a.tipo_plan, a.rutina_id
FROM usuario u
JOIN alumno a ON u.id = a.usuario_id
`

type ListAlumnosCompletosRow struct {
	ID               int32          `json:"id"`
	Email            string         `json:"email"`
	Nombre           string         `json:"nombre"`
	Apellido         string         `json:"apellido"`
	Telefono         sql.NullString `json:"telefono"`
	Rol              string         `json:"rol"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	FechaInscripcion time.Time      `json:"fecha_inscripcion"`
	FechaVto         sql.NullTime   `json:"fecha_vto"`
	TipoPlan         sql.NullString `json:"tipo_plan"`
	RutinaID         sql.NullInt32  `json:"rutina_id"`
}

func (q *Queries) ListAlumnosCompletos(ctx context.Context) ([]ListAlumnosCompletosRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlumnosCompletos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlumnosCompletosRow
	for rows.Next() {
		var i ListAlumnosCompletosRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Nombre,
			&i.Apellido,
			&i.Telefono,
			&i.Rol,
			&i.CreatedAt,
			&i.FechaInscripcion,
			&i.FechaVto,
			&i.TipoPlan,
			&i.RutinaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlumnoDetalles = `-- name: UpdateAlumnoDetalles :exec
UPDATE alumno
SET fecha_vto = $1, tipo_plan = $2, rutina_id = $3
WHERE usuario_id = $4
`

type UpdateAlumnoDetallesParams struct {
	FechaVto  sql.NullTime   `json:"fecha_vto"`
	TipoPlan  sql.NullString `json:"tipo_plan"`
	RutinaID  sql.NullInt32  `json:"rutina_id"`
	UsuarioID int32          `json:"usuario_id"`
}

func (q *Queries) UpdateAlumnoDetalles(ctx context.Context, arg UpdateAlumnoDetallesParams) error {
	_, err := q.db.ExecContext(ctx, updateAlumnoDetalles,
		arg.FechaVto,
		arg.TipoPlan,
		arg.RutinaID,
		arg.UsuarioID,
	)
	return err
}
