// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clase.sql

package db

import (
	"context"
	"time"
)

const createClase = `-- name: CreateClase :one

INSERT INTO clase (nombre, max_alumnos, profesor_id)
VALUES ($1, $2, $3)
RETURNING id, nombre, max_alumnos, profesor_id
`

type CreateClaseParams struct {
	Nombre     string `json:"nombre"`
	MaxAlumnos int32  `json:"max_alumnos"`
	ProfesorID int32  `json:"profesor_id"`
}

// CONSULTAS DE CLASE
func (q *Queries) CreateClase(ctx context.Context, arg CreateClaseParams) (Clase, error) {
	row := q.db.QueryRowContext(ctx, createClase, arg.Nombre, arg.MaxAlumnos, arg.ProfesorID)
	var i Clase
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MaxAlumnos,
		&i.ProfesorID,
	)
	return i, err
}

const createClaseHorario = `-- name: CreateClaseHorario :one
INSERT INTO clase_horario (clase_id, dia_semana, hora_inicio)
VALUES ($1, $2, $3)
RETURNING id, clase_id, dia_semana, hora_inicio
`

type CreateClaseHorarioParams struct {
	ClaseID    int32     `json:"clase_id"`
	DiaSemana  string    `json:"dia_semana"`
	HoraInicio time.Time `json:"hora_inicio"`
}

func (q *Queries) CreateClaseHorario(ctx context.Context, arg CreateClaseHorarioParams) (ClaseHorario, error) {
	row := q.db.QueryRowContext(ctx, createClaseHorario, arg.ClaseID, arg.DiaSemana, arg.HoraInicio)
	var i ClaseHorario
	err := row.Scan(
		&i.ID,
		&i.ClaseID,
		&i.DiaSemana,
		&i.HoraInicio,
	)
	return i, err
}

const deleteClase = `-- name: DeleteClase :exec
DELETE FROM clase
WHERE id = $1
`

func (q *Queries) DeleteClase(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteClase, id)
	return err
}

const deleteClaseHorario = `-- name: DeleteClaseHorario :exec
DELETE FROM clase_horario
WHERE id = $1
`

func (q *Queries) DeleteClaseHorario(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteClaseHorario, id)
	return err
}

const getClase = `-- name: GetClase :one
SELECT id, nombre, max_alumnos, profesor_id
FROM clase
WHERE id = $1
`

func (q *Queries) GetClase(ctx context.Context, id int32) (Clase, error) {
	row := q.db.QueryRowContext(ctx, getClase, id)
	var i Clase
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.MaxAlumnos,
		&i.ProfesorID,
	)
	return i, err
}

const getClaseHorario = `-- name: GetClaseHorario :one
SELECT id, clase_id, dia_semana, hora_inicio
FROM clase_horario
WHERE id = $1
`

func (q *Queries) GetClaseHorario(ctx context.Context, id int32) (ClaseHorario, error) {
	row := q.db.QueryRowContext(ctx, getClaseHorario, id)
	var i ClaseHorario
	err := row.Scan(
		&i.ID,
		&i.ClaseID,
		&i.DiaSemana,
		&i.HoraInicio,
	)
	return i, err
}

const listClases = `-- name: ListClases :many
SELECT id, nombre, max_alumnos, profesor_id
FROM clase
`

func (q *Queries) ListClases(ctx context.Context) ([]Clase, error) {
	rows, err := q.db.QueryContext(ctx, listClases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clase
	for rows.Next() {
		var i Clase
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.MaxAlumnos,
			&i.ProfesorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHorariosDeClase = `-- name: ListHorariosDeClase :many
SELECT id, clase_id, dia_semana, hora_inicio
FROM clase_horario
WHERE clase_id = $1
`

func (q *Queries) ListHorariosDeClase(ctx context.Context, claseID int32) ([]ClaseHorario, error) {
	rows, err := q.db.QueryContext(ctx, listHorariosDeClase, claseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaseHorario
	for rows.Next() {
		var i ClaseHorario
		if err := rows.Scan(
			&i.ID,
			&i.ClaseID,
			&i.DiaSemana,
			&i.HoraInicio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClase = `-- name: UpdateClase :exec
UPDATE clase
SET nombre = $1, max_alumnos = $2
WHERE id = $3
`

type UpdateClaseParams struct {
	Nombre     string `json:"nombre"`
	MaxAlumnos int32  `json:"max_alumnos"`
	ID         int32  `json:"id"`
}

func (q *Queries) UpdateClase(ctx context.Context, arg UpdateClaseParams) error {
	_, err := q.db.ExecContext(ctx, updateClase, arg.Nombre, arg.MaxAlumnos, arg.ID)
	return err
}
