// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ejercicios.sql

package db

import (
	"context"
	"database/sql"
)

const createEjercicio = `-- name: CreateEjercicio :one

INSERT INTO ejercicios (nombre, descripcion)
VALUES ($1, $2)
RETURNING id, nombre, descripcion
`

type CreateEjercicioParams struct {
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
}

// CONSULTAS DE EJERCICIOS
func (q *Queries) CreateEjercicio(ctx context.Context, arg CreateEjercicioParams) (Ejercicio, error) {
	row := q.db.QueryRowContext(ctx, createEjercicio, arg.Nombre, arg.Descripcion)
	var i Ejercicio
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const deleteEjercicio = `-- name: DeleteEjercicio :exec
DELETE FROM ejercicios
WHERE id = $1
`

func (q *Queries) DeleteEjercicio(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEjercicio, id)
	return err
}

const getEjercicio = `-- name: GetEjercicio :one
SELECT id, nombre, descripcion
FROM ejercicios
WHERE id = $1
`

func (q *Queries) GetEjercicio(ctx context.Context, id int32) (Ejercicio, error) {
	row := q.db.QueryRowContext(ctx, getEjercicio, id)
	var i Ejercicio
	err := row.Scan(&i.ID, &i.Nombre, &i.Descripcion)
	return i, err
}

const listEjercicios = `-- name: ListEjercicios :many
SELECT id, nombre, descripcion
FROM ejercicios
`

func (q *Queries) ListEjercicios(ctx context.Context) ([]Ejercicio, error) {
	rows, err := q.db.QueryContext(ctx, listEjercicios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ejercicio
	for rows.Next() {
		var i Ejercicio
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEjercicio = `-- name: UpdateEjercicio :exec
UPDATE ejercicios
SET nombre = $1, descripcion = $2
WHERE id = $3
`

type UpdateEjercicioParams struct {
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
	ID          int32          `json:"id"`
}

func (q *Queries) UpdateEjercicio(ctx context.Context, arg UpdateEjercicioParams) error {
	_, err := q.db.ExecContext(ctx, updateEjercicio, arg.Nombre, arg.Descripcion, arg.ID)
	return err
}
