// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inscripcion_clase.sql

package db

import (
	"context"
)

const createInscripcion = `-- name: CreateInscripcion :one
INSERT INTO inscripcion_clase (clase_horario_id, alumno_id)
VALUES ($1, $2)
RETURNING clase_horario_id, alumno_id, fecha_inscripcion
`

type CreateInscripcionParams struct {
	ClaseHorarioID int32 `json:"clase_horario_id"`
	AlumnoID       int32 `json:"alumno_id"`
}

func (q *Queries) CreateInscripcion(ctx context.Context, arg CreateInscripcionParams) (InscripcionClase, error) {
	row := q.db.QueryRowContext(ctx, createInscripcion, arg.ClaseHorarioID, arg.AlumnoID)
	var i InscripcionClase
	err := row.Scan(&i.ClaseHorarioID, &i.AlumnoID, &i.FechaInscripcion)
	return i, err
}

const deleteInscripcion = `-- name: DeleteInscripcion :exec
DELETE FROM inscripcion_clase
WHERE clase_horario_id = $1 AND alumno_id = $2
`

type DeleteInscripcionParams struct {
	ClaseHorarioID int32 `json:"clase_horario_id"`
	AlumnoID       int32 `json:"alumno_id"`
}

func (q *Queries) DeleteInscripcion(ctx context.Context, arg DeleteInscripcionParams) error {
	_, err := q.db.ExecContext(ctx, deleteInscripcion, arg.ClaseHorarioID, arg.AlumnoID)
	return err
}

const getCupoDeHorario = `-- name: GetCupoDeHorario :one
SELECT c.max_alumnos,
       COUNT(ic.alumno_id)::int AS cantidad_inscriptos
FROM clase_horario ch
JOIN clase c ON c.id = ch.clase_id
LEFT JOIN inscripcion_clase ic ON ic.clase_horario_id = ch.id
WHERE ch.id = $1
GROUP BY c.max_alumnos
`

type GetCupoDeHorarioRow struct {
	MaxAlumnos         int32 `json:"max_alumnos"`
	CantidadInscriptos int32 `json:"cantidad_inscriptos"`
}

func (q *Queries) GetCupoDeHorario(ctx context.Context, id int32) (GetCupoDeHorarioRow, error) {
	row := q.db.QueryRowContext(ctx, getCupoDeHorario, id)
	var i GetCupoDeHorarioRow
	err := row.Scan(&i.MaxAlumnos, &i.CantidadInscriptos)
	return i, err
}

const listInscriptos = `-- name: ListInscriptos :many
SELECT ic.alumno_id, u.nombre, u.apellido
FROM inscripcion_clase ic
JOIN alumno a ON ic.alumno_id = a.usuario_id
JOIN usuario u ON a.usuario_id = u.id
WHERE ic.clase_horario_id = $1
`

type ListInscriptosRow struct {
	AlumnoID int32  `json:"alumno_id"`
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
}

func (q *Queries) ListInscriptos(ctx context.Context, claseHorarioID int32) ([]ListInscriptosRow, error) {
	rows, err := q.db.QueryContext(ctx, listInscriptos, claseHorarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInscriptosRow
	for rows.Next() {
		var i ListInscriptosRow
		if err := rows.Scan(&i.AlumnoID, &i.Nombre, &i.Apellido); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
