// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Alumno struct {
	UsuarioID        int32          `json:"usuario_id"`
	FechaInscripcion time.Time      `json:"fecha_inscripcion"`
	FechaVto         sql.NullTime   `json:"fecha_vto"`
	TipoPlan         sql.NullString `json:"tipo_plan"`
	RutinaID         sql.NullInt32  `json:"rutina_id"`
}

type Clase struct {
	ID         int32         `json:"id"`
	Dias       string        `json:"dias"`
	Hora       time.Time     `json:"hora"`
	MaxAlumnos int32         `json:"max_alumnos"`
	ProfesorID sql.NullInt32 `json:"profesor_id"`
}

type Ejercicio struct {
	ID          int32          `json:"id"`
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
}

type InscripcionesClase struct {
	ClaseID  int32     `json:"clase_id"`
	AlumnoID int32     `json:"alumno_id"`
	Dia      string    `json:"dia"`
	Hora     time.Time `json:"hora"`
}

type Profesore struct {
	UsuarioID    int32          `json:"usuario_id"`
	Horario      sql.NullString `json:"horario"`
	Especialidad sql.NullString `json:"especialidad"`
}

type Rutina struct {
	ID              int32 `json:"id"`
	DuracionSemanas int32 `json:"duracion_semanas"`
}

type RutinaEjercicio struct {
	RutinaID    int32 `json:"rutina_id"`
	EjercicioID int32 `json:"ejercicio_id"`
}

type Usuario struct {
	ID         int32          `json:"id"`
	Email      string         `json:"email"`
	Contrasena string         `json:"contrasena"`
	Nombre     string         `json:"nombre"`
	Apellido   string         `json:"apellido"`
	Telefono   sql.NullString `json:"telefono"`
	Rol        string         `json:"rol"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}
