// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: multitabla.sql

package db

import (
	"context"
	"time"
)

const clasesProfesor = `-- name: ClasesProfesor :many
SELECT
    u.nombre,
    u.apellido,
    c.nombre AS clase_nombre,
    c.max_alumnos,
    ch.dia_semana,
    ch.hora_inicio
FROM clase c
JOIN profesor p ON c.profesor_id = p.usuario_id
JOIN usuario u ON p.usuario_id = u.id
JOIN clase_horario ch ON ch.clase_id = c.id
WHERE c.profesor_id = $1
`

type ClasesProfesorRow struct {
	Nombre      string    `json:"nombre"`
	Apellido    string    `json:"apellido"`
	ClaseNombre string    `json:"clase_nombre"`
	MaxAlumnos  int32     `json:"max_alumnos"`
	DiaSemana   string    `json:"dia_semana"`
	HoraInicio  time.Time `json:"hora_inicio"`
}

func (q *Queries) ClasesProfesor(ctx context.Context, profesorID int32) ([]ClasesProfesorRow, error) {
	rows, err := q.db.QueryContext(ctx, clasesProfesor, profesorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClasesProfesorRow
	for rows.Next() {
		var i ClasesProfesorRow
		if err := rows.Scan(
			&i.Nombre,
			&i.Apellido,
			&i.ClaseNombre,
			&i.MaxAlumnos,
			&i.DiaSemana,
			&i.HoraInicio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEjerciciosRutina = `-- name: ListEjerciciosRutina :many
SELECT e.id, e.nombre, e.descripcion, e.grupo_muscular
FROM rutina_ejercicio re
JOIN ejercicio e ON re.ejercicio_id = e.id
WHERE re.rutina_id = $1
`

func (q *Queries) ListEjerciciosRutina(ctx context.Context, rutinaID int32) ([]Ejercicio, error) {
	rows, err := q.db.QueryContext(ctx, listEjerciciosRutina, rutinaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ejercicio
	for rows.Next() {
		var i Ejercicio
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.GrupoMuscular,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profesoresdelDia = `-- name: ProfesoresdelDia :many
SELECT DISTINCT u.nombre, u.apellido
FROM profesor p
JOIN usuario u ON p.usuario_id = u.id
JOIN clase c ON c.profesor_id = p.usuario_id
JOIN clase_horario ch ON ch.clase_id = c.id
WHERE ch.dia_semana = $1
`

type ProfesoresdelDiaRow struct {
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
}

func (q *Queries) ProfesoresdelDia(ctx context.Context, diaSemana string) ([]ProfesoresdelDiaRow, error) {
	rows, err := q.db.QueryContext(ctx, profesoresdelDia, diaSemana)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfesoresdelDiaRow
	for rows.Next() {
		var i ProfesoresdelDiaRow
		if err := rows.Scan(&i.Nombre, &i.Apellido); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
