// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profesor.sql

package db

import (
	"context"
	"database/sql"
)

const getProfesorCompleto = `-- name: GetProfesorCompleto :one
SELECT
    u.id, u.email, u.nombre, u.apellido, u.telefono, u.rol, u.created_at,
    p.especialidad
FROM usuario u
JOIN profesor p ON u.id = p.usuario_id
WHERE u.id = $1
`

type GetProfesorCompletoRow struct {
	ID           int32          `json:"id"`
	Email        string         `json:"email"`
	Nombre       string         `json:"nombre"`
	Apellido     string         `json:"apellido"`
	Telefono     sql.NullString `json:"telefono"`
	Rol          string         `json:"rol"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	Especialidad sql.NullString `json:"especialidad"`
}

func (q *Queries) GetProfesorCompleto(ctx context.Context, id int32) (GetProfesorCompletoRow, error) {
	row := q.db.QueryRowContext(ctx, getProfesorCompleto, id)
	var i GetProfesorCompletoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.Apellido,
		&i.Telefono,
		&i.Rol,
		&i.CreatedAt,
		&i.Especialidad,
	)
	return i, err
}

const insertProfesor = `-- name: InsertProfesor :exec

INSERT INTO profesor (usuario_id, especialidad)
VALUES ($1, $2)
`

type InsertProfesorParams struct {
	UsuarioID    int32          `json:"usuario_id"`
	Especialidad sql.NullString `json:"especialidad"`
}

// CONSULTAS DE PROFESOR
func (q *Queries) InsertProfesor(ctx context.Context, arg InsertProfesorParams) error {
	_, err := q.db.ExecContext(ctx, insertProfesor, arg.UsuarioID, arg.Especialidad)
	return err
}

const listProfesoresCompletos = `-- name: ListProfesoresCompletos :many
SELECT
    u.id, u.email, u.nombre, u.apellido, u.telefono, u.rol, u.created_at,
    p.especialidad
FROM usuario u
JOIN profesor p ON u.id = p.usuario_id
`

type ListProfesoresCompletosRow struct {
	ID           int32          `json:"id"`
	Email        string         `json:"email"`
	Nombre       string         `json:"nombre"`
	Apellido     string         `json:"apellido"`
	Telefono     sql.NullString `json:"telefono"`
	Rol          string         `json:"rol"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	Especialidad sql.NullString `json:"especialidad"`
}

func (q *Queries) ListProfesoresCompletos(ctx context.Context) ([]ListProfesoresCompletosRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfesoresCompletos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfesoresCompletosRow
	for rows.Next() {
		var i ListProfesoresCompletosRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Nombre,
			&i.Apellido,
			&i.Telefono,
			&i.Rol,
			&i.CreatedAt,
			&i.Especialidad,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfesor = `-- name: UpdateProfesor :exec
UPDATE profesor
SET especialidad = $1
WHERE usuario_id = $2
`

type UpdateProfesorParams struct {
	Especialidad sql.NullString `json:"especialidad"`
	UsuarioID    int32          `json:"usuario_id"`
}

func (q *Queries) UpdateProfesor(ctx context.Context, arg UpdateProfesorParams) error {
	_, err := q.db.ExecContext(ctx, updateProfesor, arg.Especialidad, arg.UsuarioID)
	return err
}
