// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rutina.sql

package db

import (
	"context"
	"database/sql"
)

const addEjercicioARutina = `-- name: AddEjercicioARutina :exec
INSERT INTO rutina_ejercicio (rutina_id, ejercicio_id, orden, series, repeticiones, descanso_segundos)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AddEjercicioARutinaParams struct {
	RutinaID         int32         `json:"rutina_id"`
	EjercicioID      int32         `json:"ejercicio_id"`
	Orden            int32         `json:"orden"`
	Series           sql.NullInt32 `json:"series"`
	Repeticiones     sql.NullInt32 `json:"repeticiones"`
	DescansoSegundos sql.NullInt32 `json:"descanso_segundos"`
}

func (q *Queries) AddEjercicioARutina(ctx context.Context, arg AddEjercicioARutinaParams) error {
	_, err := q.db.ExecContext(ctx, addEjercicioARutina,
		arg.RutinaID,
		arg.EjercicioID,
		arg.Orden,
		arg.Series,
		arg.Repeticiones,
		arg.DescansoSegundos,
	)
	return err
}

const createRutina = `-- name: CreateRutina :one

INSERT INTO rutina (nombre, duracion_semanas, profesor_id)
VALUES ($1, $2, $3)
RETURNING id, nombre, duracion_semanas, profesor_id
`

type CreateRutinaParams struct {
	Nombre          string `json:"nombre"`
	DuracionSemanas int32  `json:"duracion_semanas"`
	ProfesorID      int32  `json:"profesor_id"`
}

// CONSULTAS DE RUTINA
func (q *Queries) CreateRutina(ctx context.Context, arg CreateRutinaParams) (Rutina, error) {
	row := q.db.QueryRowContext(ctx, createRutina, arg.Nombre, arg.DuracionSemanas, arg.ProfesorID)
	var i Rutina
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.DuracionSemanas,
		&i.ProfesorID,
	)
	return i, err
}

const deleteEjercicioDeRutina = `-- name: DeleteEjercicioDeRutina :exec
DELETE FROM rutina_ejercicio
WHERE rutina_id = $1 AND ejercicio_id = $2
`

type DeleteEjercicioDeRutinaParams struct {
	RutinaID    int32 `json:"rutina_id"`
	EjercicioID int32 `json:"ejercicio_id"`
}

func (q *Queries) DeleteEjercicioDeRutina(ctx context.Context, arg DeleteEjercicioDeRutinaParams) error {
	_, err := q.db.ExecContext(ctx, deleteEjercicioDeRutina, arg.RutinaID, arg.EjercicioID)
	return err
}

const deleteRutina = `-- name: DeleteRutina :exec
DELETE FROM rutina
WHERE id = $1
`

func (q *Queries) DeleteRutina(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteRutina, id)
	return err
}

const getRutina = `-- name: GetRutina :one
SELECT id, nombre, duracion_semanas, profesor_id
FROM rutina
WHERE id = $1
`

func (q *Queries) GetRutina(ctx context.Context, id int32) (Rutina, error) {
	row := q.db.QueryRowContext(ctx, getRutina, id)
	var i Rutina
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.DuracionSemanas,
		&i.ProfesorID,
	)
	return i, err
}

const listRutinas = `-- name: ListRutinas :many
SELECT id, nombre, duracion_semanas, profesor_id
FROM rutina
`

func (q *Queries) ListRutinas(ctx context.Context) ([]Rutina, error) {
	rows, err := q.db.QueryContext(ctx, listRutinas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rutina
	for rows.Next() {
		var i Rutina
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.DuracionSemanas,
			&i.ProfesorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRutina = `-- name: UpdateRutina :exec
UPDATE rutina
SET nombre = $1, duracion_semanas = $2
WHERE id = $3
`

type UpdateRutinaParams struct {
	Nombre          string `json:"nombre"`
	DuracionSemanas int32  `json:"duracion_semanas"`
	ID              int32  `json:"id"`
}

func (q *Queries) UpdateRutina(ctx context.Context, arg UpdateRutinaParams) error {
	_, err := q.db.ExecContext(ctx, updateRutina, arg.Nombre, arg.DuracionSemanas, arg.ID)
	return err
}
