// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package db

import (
	"context"
	"database/sql"
)

const createUsuario = `-- name: CreateUsuario :one

INSERT INTO usuarios (email, contrasena, nombre, apellido, telefono, rol)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, nombre, apellido, telefono, rol, created_at
`

type CreateUsuarioParams struct {
	Email      string         `json:"email"`
	Contrasena string         `json:"contrasena"`
	Nombre     string         `json:"nombre"`
	Apellido   string         `json:"apellido"`
	Telefono   sql.NullString `json:"telefono"`
	Rol        string         `json:"rol"`
}

type CreateUsuarioRow struct {
	ID        int32          `json:"id"`
	Email     string         `json:"email"`
	Nombre    string         `json:"nombre"`
	Apellido  string         `json:"apellido"`
	Telefono  sql.NullString `json:"telefono"`
	Rol       string         `json:"rol"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

// CONSULTAS DE USUARIOS
func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (CreateUsuarioRow, error) {
	row := q.db.QueryRowContext(ctx, createUsuario,
		arg.Email,
		arg.Contrasena,
		arg.Nombre,
		arg.Apellido,
		arg.Telefono,
		arg.Rol,
	)
	var i CreateUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nombre,
		&i.Apellido,
		&i.Telefono,
		&i.Rol,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuarios
WHERE id = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, id)
	return err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id, email, contrasena, nombre, apellido, telefono, rol, created_at
FROM usuarios
WHERE id = $1
`

func (q *Queries) GetUsuario(ctx context.Context, id int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Contrasena,
		&i.Nombre,
		&i.Apellido,
		&i.Telefono,
		&i.Rol,
		&i.CreatedAt,
	)
	return i, err
}

const updateUsuario = `-- name: UpdateUsuario :exec
UPDATE usuarios
SET email = $1, contrasena = $2, nombre = $3, apellido = $4, telefono = $5
WHERE id = $6
`

type UpdateUsuarioParams struct {
	Email      string         `json:"email"`
	Contrasena string         `json:"contrasena"`
	Nombre     string         `json:"nombre"`
	Apellido   string         `json:"apellido"`
	Telefono   sql.NullString `json:"telefono"`
	ID         int32          `json:"id"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, updateUsuario,
		arg.Email,
		arg.Contrasena,
		arg.Nombre,
		arg.Apellido,
		arg.Telefono,
		arg.ID,
	)
	return err
}
